services:
  laravel:
    container_name: laravel
    build:
      context: laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel/:/var/www
    depends_on:
      - db
      - redis
      - rabbitmq
    command: ["php-fpm"]
    ports:
      - '9002:9000'
    networks:
      - app

  next:
    container_name: next
    build:
      context: next
      dockerfile: Dockerfile
    volumes:
      - ./next/:/var/app
    command: sh -c "npm run ${NEXT_RUN}"
    depends_on:
      - nginx
      - laravel
    ports:
      - '3000:3000'
    networks:
      - app

  horizon:
    container_name: horizon
    build:
      context: laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel/:/var/www
    depends_on:
      - db
      - redis
      - rabbitmq
    command: ["php","artisan","horizon"]
    profiles: 
      - workers
    restart: always
    networks:
      - app

  # schedule:
  #   container_name: schedule
  #   build:
  #     context: laravel
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./laravel/:/var/www
  #   depends_on:
  #     - db
  #     - redis
  #     - rabbitmq
  #   command: ["php", "artisan", "schedule:run"]
  #   profiles: 
  #     - workers
  #   restart: always
  #   networks:
  #     - app
  

  # db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #       MYSQL_DATABASE: ${DB_DATABASE}
  #       MYSQL_USER: ${DB_USERNAME}
  #       MYSQL_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #       - ./docker/data:/var/lib/mysql
  #   ports:
  #       - ${DB_PORT}:${DB_PORT}
  #   networks:
  #       - app

  db:
    image: postgres:15
    restart: always
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    labels:
      proxy_nginx: "ssl"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel/:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
      - /tmp/letsencrypt/www:/tmp/letsencrypt/www
    networks:
      - app

  letsencrypt:
    image: gordonchan/auto-letsencrypt
    links:
      - nginx
    volumes:
      - /var/log/letsencrypt/:/var/log/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /tmp/letsencrypt/www:/tmp/letsencrypt/www
      - ./docker/nginx/certs:/etc/nginx/certs
    environment:
      - EMAIL=my@email.com
      - SERVER_CONTAINER=nginx
      - WEBROOT_PATH=/tmp/letsencrypt/www
      - CERTS_PATH=/etc/nginx/certs
      - DOMAINS=site.com
      - CHECK_FREQ=1
      - SERVER_CONTAINER_LABEL=proxy_nginx
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: ${RABBITMQ_HOST}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
        - ${RABBITMQ_ADMIN_PORT}:${RABBITMQ_ADMIN_PORT}
        - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    restart: always
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    networks:
      - app

  redis:
      image: redis:alpine
      container_name: redis
      restart: unless-stopped
      volumes:
      - ./docker/redis:/data
      ports:
        - ${REDIS_PORT}:${REDIS_PORT}
      networks:
      - app

networks:
    app:
        name: app