import type { Metadata } from "next";
import "../styles/styles.scss";
import { Inter } from 'next/font/google'
import { Header } from "@/components/modules/header/header";
import { Footer } from "@/components/modules/footer/footer";
const inter = Inter({
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "DA-DA Тур",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
}) {

  return (
    <html lang="ru">
      <body className={`${inter.className}`}>
        <Header />
        <div className="wrapper">
          {props.children}
        </div>
        <Footer />
      </body>
    </html >
  );
}
